class IndexItem:
    productDetail={
        "graduate":{
            "src":"",
            "alt":"畢業花束",
            "title":"畢業花束"
        },
        "mother":{
            "src":"",
            "alt":"母親節花束",
            "title":"母親節花束"
        },
        "marriage":{
            "src":"",
            "alt":"求婚花束",
            "title":"求婚花束"
        },
        "dryflower":{
            "src":"",
            "alt":"乾燥花束",
            "title":"乾燥花束"
        },
        "glass":{
            "src":"",
            "alt":"玻璃罩",
            "title":"玻璃盅罩"
        },
        "decoration":{
            "src":"",
            "alt":"婚禮小物",
            "title":"裝飾小物"
        },
        "wedding":{
            "src":"",
            "alt":"婚禮捧花",
            "title":"婚禮系列"
        },
        "plants":{
            "src":"",
            "alt":"乾燥花盆花",
            "title":"盆花花禮"
        }
    }
    newType={
        "main":{
            "src":"",
            "alt":""
        },
        "procucts":{
            "item1":{
                "src":"",
                "alt":"",
                "title":""
            },
            "item2":{
                "src":"",
                "alt":"",
                "title":""
            },
            "item3":{
                "src":"",
                "alt":"",
                "title":""
            },
            "item4":{
                "src":"",
                "alt":"",
                "title":""
            }
        }
    }