class Detail:
    price={
        "marriage1":"$700",
        "marriage2":"$890",
        "marriage3":"$1200",
        "dryflower1":"$250",
        "dryflower2":"$299",
        "dryflower3":"$500",
        "glass1":"$1200",
        "glass2":"$690",
        "glass3":"$800",
        "glass4":"860",
        "decoration1":"720",
        "decoration2":"560"
    }
    description={
        "marriage1":"7朵玫瑰",
        "marriage2":"9朵玫瑰",
        "marriage3":"12朵玫瑰",
        "dryflower1":"",
        "dryflower2":"",
        "dryflower3":"",
        "glass1":"盅罩有燈款",
        "glass2":"盅罩無燈款",
        "glass3":"圓罩無燈款",
        "glass4":"圓罩有燈款",
        "decoration1":"方形框",
        "decoration2":"矩形框"
    }
    size={
        "marriage1":"花面寬約30cm(含包裝)、總長約40cm",
        "marriage2":"花面寬約35cm(含包裝)、總長約50cm",
        "marriage3":"花面寬約45cm(含包裝)、總長約60cm",
        "dryflower1":"花面寬約10cm(含包裝)、總長約25cm",
        "dryflower2":"花面寬約15cm(含包裝)、總長約30cm",
        "dryflower3":"花面寬約23cm(含包裝)、總長約35cm",
        "glass1":"外徑14cm、內徑10.5cm、總高約16.5cm",
        "glass2":"外徑10.4cm、內徑7cm、總高約15cm",
        "glass3":"外徑11.3cm、內徑8cm、總高約10cm",
        "glass4":"外徑11.3cm、內徑8cm、總高約12cm",
        "decoration1":"19.5X19.3cm",
        "decoration2":"19.5X14.4cm"
    }
    path={
        "marriage1":"/static/img/products/marriage/soap7/",
        "marriage2":"/static/img/products/marriage/soap9/",
        "marriage3":"/static/img/products/marriage/soap12/",
        "dryflower1":"/static/img/products/dryflower/",
        "dryflower2":"/static/img/products/dryflower/",
        "dryflower3":"/static/img/products/dryflower/",
        "glass1":"/static/img/products/glass/",
        "glass2":"/static/img/products/glass/",
        "glass3":"/static/img/products/glass/",
        "glass4":"/static/img/products/glass/",
        "decoration1":"/static/img/products/decoration/",
        "decoration2":"/static/img/products/decoration/"
    }
    alt={
        "marriage1":"求婚花束",
        "marriage2":"求婚花束",
        "marriage3":"求婚花束",
        "dryflower1":"乾燥花束",
        "dryflower2":"乾燥花束",
        "dryflower3":"乾燥花束",
        "glass1":"玻璃罩",
        "glass2":"玻璃罩",
        "glass3":"玻璃罩",
        "glass4":"玻璃罩",
        "decoration1":"相框",
        "decoration2":"相框"
    }
    type={
        "marriage1":"marriage",
        "marriage2":"marriage",
        "marriage3":"marriage",
        "dryflower1":"dryflower",
        "dryflower2":"dryflower",
        "dryflower3":"dryflower",
        "glass1":"glass",
        "glass2":"glass",
        "glass3":"glass",
        "glass4":"glass",
        "decoration1":"decoration",
        "decoration2":"decoration"
    }
    # 選項的顯示轉換用
    select={
        "marriage1":"求婚花束",
        "marriage2":"求婚花束",
        "marriage3":"求婚花束",
        "dryflower1":"乾燥花束",
        "dryflower2":"乾燥花束",
        "dryflower3":"乾燥花束",
        "glass1":"玻璃盅罩",
        "glass2":"玻璃盅罩",
        "glass3":"玻璃盅罩",
        "glass4":"玻璃盅罩",
        "decoration1":"裝飾小物",
        "decoration2":"裝飾小物"
    }

class IndexItem:
    productDetail={
        "graduate":{
            "url":"#",
            "src":"#",
            "alt":"畢業花束",
            "title":"畢業花束"
        },
        "mother":{
            "url":"#",
            "src":"#",
            "alt":"母親節花束",
            "title":"母親節花束"
        },
        "marriage":{
            "url":"/category/marriage",
            "src":"",
            "alt":"求婚花束",
            "title":"求婚花束"
        },
        "dryflower":{
            "url":"#",
            "src":"#",
            "alt":"乾燥花束",
            "title":"乾燥花束"
        },
        "glass":{
            "url":"#",
            "src":"#",
            "alt":"玻璃罩",
            "title":"玻璃盅罩"
        },
        "decoration":{
            "url":"#",
            "src":"#",
            "alt":"婚禮小物",
            "title":"裝飾小物"
        },
        "wedding":{
            "url":"#",
            "src":"#",
            "alt":"婚禮捧花",
            "title":"婚禮系列"
        },
        "plants":{
            "url":"#",
            "src":"#",
            "alt":"乾燥花盆花",
            "title":"盆花花禮"
        }
    }
    newType={
        "main":{
            "src":"",
            "alt":""
        },
        "procucts":{
            "item1":{
                "src":"",
                "alt":"",
                "title":""
            },
            "item2":{
                "src":"",
                "alt":"",
                "title":""
            },
            "item3":{
                "src":"",
                "alt":"",
                "title":""
            },
            "item4":{
                "src":"",
                "alt":"",
                "title":""
            }
        }
    }

    
